#!/bin/sh
set -e

case "$1" in
    purge)
        if [ -d /run/systemd/system ]; then
            systemctl --system daemon-reload >/dev/null 2>&1 || true
        fi
        rm -rf /var/lib/kadr /etc/kadr
    ;;
esac

exit 0
